version: '3.8'

services:
  frontend:
    build: ./DailyVS_client
    container_name: frontend
    ports:
      - "80:80"  # Nginx가 80번 포트를 사용
    networks:
      - dailyvs_network
    environment:
      - REACT_APP_API_BASE_URL=http://server:8000  # Django 서비스와 통신

  web:
    build: ./DailyVS_server
    container_name: server
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]
    # volumes:  # 필요 시 주석 처리 해제
    #   - ./DailyVS_server:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - PYTHONPATH=/app
    networks:
      - dailyvs_network

networks:
  dailyvs_network:
    driver: bridge