version: '3.8'

services:
  web:
    build: ./DailyVS_server
    container_name: server
    volumes:
      - ./DailyVS_server:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - PYTHONPATH=/app
    networks:
      - dailyvs_network

  frontend:
    build: ./DailyVS_client
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - dailyvs_network
    depends_on:
      - web  # Django 서버가 먼저 시작되어야 함

networks:
  dailyvs_network:
    driver: bridge
